image: mcr.microsoft.com/dotnet/sdk:latest

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - cat $NUGET_CONFIG > nuget.config
    - dotnet restore
    - dotnet build --no-restore -c Release
    - dotnet nuget push -s amget -k $AMGET_API_KEY --skip-duplicate src/Modbus.Common/bin/Release/*.nupkg
    - dotnet nuget push -s amget -k $AMGET_API_KEY --skip-duplicate src/Modbus.Tcp/bin/Release/*.nupkg
    - dotnet nuget push -s amget -k $AMGET_API_KEY --skip-duplicate src/Modbus.Serial/bin/Release/*.nupkg
    - dotnet nuget push -s amget -k $AMGET_API_KEY --skip-duplicate src/Modbus.Proxy/bin/Release/*.nupkg
  artifacts:
    paths:
      - src/Modbus.Common/bin/Release/*.nupkg
      - src/Modbus.Common/bin/Release/*.snupkg
      - src/Modbus.Tcp/bin/Release/*.nupkg
      - src/Modbus.Tcp/bin/Release/*.snupkg
      - src/Modbus.Serial/bin/Release/*.nupkg
      - src/Modbus.Serial/bin/Release/*.snupkg
      - src/Modbus.Proxy/bin/Release/*.nupkg
      - src/Modbus.Proxy/bin/Release/*.snupkg
    expire_in: 1 month

deploy:
  stage: deploy
  tags:
    - docker
  only:
    - tags
  script:
    - cat $NUGET_CONFIG > nuget.config
    - dotnet restore
    - dotnet build --no-restore -c Release
    - dotnet nuget push -s nuget -k $NUGET_API_KEY --skip-duplicate src/Modbus.Common/bin/Release/*.nupkg
    - dotnet nuget push -s nuget -k $NUGET_API_KEY --skip-duplicate src/Modbus.Tcp/bin/Release/*.nupkg
    - dotnet nuget push -s nuget -k $NUGET_API_KEY --skip-duplicate src/Modbus.Serial/bin/Release/*.nupkg
    - dotnet nuget push -s nuget -k $NUGET_API_KEY --skip-duplicate src/Modbus.Proxy/bin/Release/*.nupkg
